import { Team } from "@/types/team";

const teamData: Team[] = [
  {
    id: 1,
    name: "Manish Shaw",
    designation: "Full-stack Developer",
    image: "/images/blog/blog-01.jpg",
    bio: "Manish is a full-stack developer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    id: 2,
    name: "Ajeet Shaw",
    designation: "Full-stack Developer",
    image: "/images/blog/blog-01.jpg",
    bio: "Manish is a full-stack developer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    id: 3,
    name: "Ajeet Shaw",
    designation: "Full-stack Developer",
    image: "/images/blog/blog-01.jpg",
    bio: "Manish is a full-stack developer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    id: 4,
    name: "Ajeet Shaw",
    designation: "Full-stack Developer",
    image: "/images/blog/blog-01.jpg",
    bio: "Manish is a full-stack developer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    id: 4,
    name: "Ajeet Shaw",
    designation: "Full-stack Developer",
    image: "/images/blog/blog-01.jpg",
    bio: "Manish is a full-stack developer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    id: 4,
    name: "Ajeet Shaw",
    designation: "Full-stack Developer",
    image: "/images/blog/blog-01.jpg",
    bio: "Manish is a full-stack developer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    id: 4,
    name: "Ajeet Shaw",
    designation: "Full-stack Developer",
    image: "/images/blog/blog-01.jpg",
    bio: "Manish is a full-stack developer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
  {
    id: 4,
    name: "Ajeet Shaw",
    designation: "Full-stack Developer",
    image: "/images/blog/blog-01.jpg",
    bio: "Manish is a full-stack developer",
    facebook: "",
    instagram: "",
    linkedin: "",
    twitter: "",
  },
];

export default teamData;
